char = "#"

# Letter C
print(f" {char*4}")
print(f"{char}")
print(f"{char}")
print(f"{char}")
print(f" {char*4}")
print("")
# Letter O
print(f" {char*4}")
print(f"{char}    {char}")
print(f"{char}    {char}")
print(f"{char}    {char}")
print(f" {char*4}")
print("")
# Letter D
print(f"{char*4}")
print(f"{char}   {char}")
print(f"{char}    {char}")
print(f"{char}   {char}")
print(f"{char*4}")
print("")
# Letter E
print(f"{char*5}")
print(f"{char}")
print(f"{char*4}")
print(f"{char}")
print(f"{char*5}")
print("")
print("")
print("")
print("")
print("")
# Letter S
print(f"{char*5}")
print(f"{char}")
print(f"{char*5}")
print(f"    {char}")
print(f"{char*5}")
print("")
# Letter K
print(f"{char}    {char}")
print(f"{char}   {char}")
print(f"{char*3}")
print(f"{char}   {char}")
print(f"{char}    {char}")
print("")
# Letter Y
print(f"{char}   {char}")
print(f" {char} {char} ")
print(f"  {char}  ")
print(f"  {char}  ")
print(f"  {char}  ")
print("")
# Letter L
print(f"{char}")
print(f"{char}")
print(f"{char}")
print(f"{char}")
print(f"{char*5}")
print("")
# Letter E
print(f"{char*5}")
print(f"{char}")
print(f"{char*4}")
print(f"{char}")
print(f"{char*5}")
print("")
# Letter R
print(f"{char*4}")
print(f"{char}   {char}")
print(f"{char*4}")
print(f"{char}  {char}")
print(f"{char}   {char}")